### PR TITLE
feat: enable turn on/off animations via props

### PR DESCRIPTION
**Pull request by nafisholeh**
## Summary

Allow app to disable all animations. This can be used for perf (e.g. disable animations on slower Androids)

Closes: https://app.asana.com/0/1201136607780206/1201685881696401/f

## Test plan

Given developer add `animateOff` props to some `<Behavior>` components with any animation presets
Then there should be no animations running on that components

## Screenshots

See demo on animations of portfolio popup on the top left side of the screen:

Before: https://www.loom.com/share/15d3855ec5764e32a18feb2588667fc1
After: https://www.loom.com/share/1a6a3547e2bb41fc8dd33fa78c09c528 

## Further comments

The update here is required so that we can disable majority of animations on exodus-mobile repo. I am also open to some alternative naming beside `animateOff` if necessary.

## Checklist

- [x] The PR title follows the [conventions](https://eng-handbook.exodus-prod.io/docs/engineering/processes/your-first-pr#pr-title).
- [x] I linked the PR to an Asana task.
- [x] I added the corresponding labels and reviewers.
- [x] I reviewed my code before requesting other's reviews.
- [x] I followed the test plan myself.
- [ ] If applicable, I updated the documentation.
- [ ] If applicable, I mirrored the PR in [exodus-desktop](https://github.com/ExodusMovement/exodus-desktop) and included the link to the mirror PR in this description.

### CODE REVIEW

**Review by andrejborstnik — APPROVED** [review]
utACK

@nafisholeh can you test(on a real Android device) how long it takes to switch `animateOff` on/off for all uses via a button 🙏

**Comment by nafisholeh** [comment]
> utACK
> 
> @nafisholeh can you test(on a real Android device) how long it takes to switch `animateOff` on/off for all uses via a button 🙏

will do 👍 @andrejborstnik, thanks for the approval!
I will post the result via ticket comments as well.

**Comment by sonaye** [comment]
Can we change the prop name to `freeze`, @andrejborstnik feel free to merge and publish

**Comment by nafisholeh** [comment]
> Can we change the prop name to `freeze`, @andrejborstnik feel free to merge and publish

done on [bc00279](https://github.com/ExodusMovement/haraka/pull/15/commits/bc00279e48778bc1f984dcef16214a5feb7fb0b1)

**Review by andrejborstnik — APPROVED** [review]

**Pull request merged**
